/** Shapes shared by the orchestrator, generated by hand from the frozen contracts. */

export type Axis = "spend" | "charges" | "counterparty_match" | "period" | "scope" | "reference";

export interface Alternative {
  axis: Axis;
  reading: string;
  value: number | null;
}

export interface Verdict {
  status: "Stable" | "Sensitive" | "Fragile";
  max_variance_pct: number;
  axis: Axis | null;
  materiality_ok: boolean;
  single_reading: boolean;
  thresholds: { stable: number; sensitive: number };
}

export interface Clarification {
  question: string;
  options: { label: string; plan_patch?: Record<string, unknown> | null }[];
}

export interface Refusal {
  reason: string;
  can_do: string[];
}

export interface VerifiedResultPackage {
  question: string;
  answer_value: number | null;
  answer_unit: "INR" | "count" | "none";
  period_label: string | null;
  interpretation_text: string;
  verdict: Verdict;
  alternatives: (Alternative & { variance_pct: number })[];
  breakdown: { key: string; value: number; count?: number }[];
  evidence_ref: string | null;
  anomalies: { kind: string; subject: string; ratio: number; baseline_periods: number }[];
  allowed_numbers: number[];
  clarification: Clarification | null;
  refusal: Refusal | null;
  explanation: string;
  explanation_source: "model" | "template";
}

export interface QueryPlan {
  intent?: string;
  metric?: string;
  filters?: Record<string, any>;
  group_by?: string;
  sort?: string;
  limit?: number;
  interpretation?: Record<string, string>;
  run_alternatives?: boolean;
  run_anomaly?: boolean;
  conversation_id?: string;
  turn?: number;
  clarification?: Clarification;
  refusal?: Refusal;
}

export interface TheatreEvent {
  stage: "understand" | "verify" | "compute" | "test" | "answer";
  state: "start" | "progress" | "done" | "skipped" | "error";
  artifact?: unknown;
  note?: string | null;
  ts: number;
}
